# Generated by Django 4.0.5 on 2022-06-11 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('familia', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='familiar1',
            new_name='familiar',
        ),
    ]
